basePath: /
definitions:
  orderstreamrest_internal_models_dto.AuthErrorResponse:
    properties:
      code:
        example: 401
        type: integer
      error:
        example: unauthorized
        type: string
      login_url:
        example: /auth/login
        type: string
      message:
        example: Token de autorização inválido ou expirado
        type: string
      request_id:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  orderstreamrest_internal_models_dto.ErrorResponse:
    properties:
      code:
        type: integer
      details: {}
      error:
        type: string
      message:
        type: string
      request_id:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  orderstreamrest_internal_models_dto.HealthResponse:
    properties:
      checks:
        additionalProperties:
          type: string
        type: object
      request_id:
        type: string
      service:
        example: VisionData API
        type: string
      status:
        example: OK
        type: string
      success:
        type: boolean
      timestamp:
        type: string
      uptime:
        example: 1h30m45s
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
  orderstreamrest_internal_models_dto.MetricValue:
    properties:
      name:
        type: string
      value:
        type: integer
    type: object
  orderstreamrest_internal_models_dto.RateLimitErrorResponse:
    properties:
      code:
        example: 429
        type: integer
      error:
        example: rate_limit_exceeded
        type: string
      limit:
        example: 100
        type: integer
      message:
        example: Limite de requisições excedido
        type: string
      remaining:
        example: 0
        type: integer
      request_id:
        type: string
      reset_time:
        example: "2024-01-01T12:01:00Z"
        type: string
      retry_after:
        example: 60s
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
  orderstreamrest_internal_models_dto.TicketsMetricsResponse:
    properties:
      metrics:
        items:
          $ref: '#/definitions/orderstreamrest_internal_models_dto.TypeMetric'
        type: array
      totalTickets:
        type: integer
    type: object
  orderstreamrest_internal_models_dto.TypeMetric:
    properties:
      name:
        type: string
      values:
        items:
          $ref: '#/definitions/orderstreamrest_internal_models_dto.MetricValue'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: https://github.com/iNineBD
    name: Inine
  description: API REST para aplicação VisionData com recursos de autenticação, rate
    limiting e monitoramento.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VisionData API
  version: "1.0"
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: Verifica a saúde do serviço. Endpoint protegido com autenticação
        e rate limiting.
      produces:
      - application/json
      responses:
        "200":
          description: Status do serviço
          headers:
            X-RateLimit-Limit:
              description: Limite de requests por minuto
              type: string
            X-RateLimit-Remaining:
              description: Requests restantes no período
              type: string
            X-RateLimit-Reset:
              description: Timestamp do reset do rate limit
              type: string
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.HealthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
        "401":
          description: Unauthorized - Token inválido
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.AuthErrorResponse'
        "403":
          description: Forbidden - Sem permissão
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
        "429":
          description: Rate limit excedido
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.RateLimitErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Health Check
      tags:
      - health
  /metrics/tickets:
    get:
      consumes:
      - application/json
      description: Retorna métricas agregadas dos tickets por categoria, prioridade,
        canal e tag
      produces:
      - application/json
      responses:
        "200":
          description: Tickets metrics retrieved successfully
          headers:
            X-RateLimit-Limit:
              description: Requests per minute limit
              type: string
            X-RateLimit-Remaining:
              description: Remaining requests in the period
              type: string
            X-RateLimit-Reset:
              description: Rate limit reset timestamp
              type: string
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.TicketsMetricsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
        "401":
          description: Unauthorized - Invalid token
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.AuthErrorResponse'
        "403":
          description: Forbidden - No permission
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.RateLimitErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/orderstreamrest_internal_models_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Métricas de Tickets
      tags:
      - metrics
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
