name: golangci-lint
on:
  pull_request:
    branches:
      - 'feature/**'
      - 'sprint/**'
      - develop
      - main
      - prod
  push:
    branches:
      - 'feature/**'
      - develop
      - 'sprint/**'
      - main
      - prod

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
